name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm install && npm run build
        env:
            REACT_APP_ONGAQ_JS_KEY: ${{secrets.REACT_APP_ONGAQ_JS_KEY}}